In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,6])  #1D Array

array([1, 2, 3, 4, 5, 6])

In [3]:
a = np.array([2,3,4,5,6,7,8])  #Vector

In [4]:
print(a)

[2 3 4 5 6 7 8]


In [5]:
type(a)

numpy.ndarray

In [6]:
#2D array (Matrix)

new = np.array([[3,4,5,6,7],[7,4,6,5,2]])
print(new)

[[3 4 5 6 7]
 [7 4 6 5 2]]


In [7]:
#3D --#Tensor
np.array([[1,2,3],[4,5,6],[7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# dtype

## The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence

In [8]:
np.array([11,22,33], dtype = float)

array([11., 22., 33.])

In [9]:
np.array([11,22,33], dtype = bool)

array([ True,  True,  True])

In [10]:
np.array([11,22,33,44], dtype = complex)

array([11.+0.j, 22.+0.j, 33.+0.j, 44.+0.j])

# Numpy Arrays Vs Python Sequences
## NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).Changing the size of an ndarray will create a new array and delete the original.
## The elements in a NumPy array are all required to be of the same data type, and thus will bethe same size in memory.
## NumPy arrays facilitate advanced mathematical and other types of operations on largenumbers of data. Typically, such operations are executed more efficiently and with less codethan is possible using Python’s built-in sequences.

# Arange

In [11]:
np.arange(1,25)  #1 is included , 25 is excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [12]:
np.arange(1,25,2) #strides ---> Alternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# Reshape

Both of number products should be equal to number of items present inside the array.

In [14]:
np.arange(1,11).reshape(5,2)  #converted 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
np.arange(1,11).reshape(2,5)   #converted 2 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
np.arange(1,13).reshape(3,4)   #converted 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Ones & Zero 

You can initialize the values and create values. ex: in deep learning weight shape

In [17]:
# np.ones and np.zeros
np.ones((3,4))   #we have to mention inside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# Another Type: random()

np.random.random((3,4))

array([[0.98693578, 0.01781531, 0.827541  , 0.37888795],
       [0.66237541, 0.06729753, 0.33293774, 0.71234995],
       [0.09015662, 0.78068997, 0.88111955, 0.17550897]])

# Linespace

It is also called as linearly space, Linearly seperable, in a given range of equal distance it creates points.

In [21]:
np.linspace(-10,10,10)  #here: lower range, upper range, no. of item to generate


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# Identity

indentity matrix is that diagonal items will be ones and everything will be zero

In [25]:
# creating the identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

# Array attributes

In [4]:
a1 = np.arange(10)  #1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a2 = np.arange(12, dtype = float).reshape(3,4)  #matrix
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [10]:
a3 = np.arange(8).reshape(2,2,2) #3D:Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim

To find the arrays no. of dimensions

In [12]:
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

# shape

Gives each items consist of no. of rows and no. of columns

In [15]:
a1.shape

(10,)

In [17]:
a2.shape  #3rows and 4 columns

(3, 4)

In [19]:
a3.shape   #first 2 says it consist 2D arrays. 2,2 gives no. of rows and columns

(2, 2, 2)

# size

gives the number of items

In [20]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
a3.size

8

In [22]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [23]:
a2.size

12

# itemsize

memory occupied by the item

In [24]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1.itemsize  # in bytes

4

In [26]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
a2.itemsize   #integer 64 gives = 8 bytes

8

In [29]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a3.itemsize   #integer 32 gives = 4 bytes

4

# dtype

Gives data type of the item

In [32]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing the datatype

In [38]:
#astype
x = np.array([2,3.3,2,3.5,6])
x

array([2. , 3.3, 2. , 3.5, 6. ])

In [39]:
x.astype(int)

array([2, 3, 2, 3, 6])

In [37]:
print(type(x))

<class 'numpy.ndarray'>


# Array operations

In [2]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [3]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Scaler operations

Scaler operations on Numpy arrays include performing addition or subtraction, or multiplication on each element of a Numpy array.

In [5]:
#arithemtic
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [6]:
#substraction
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [7]:
#Multiplication
z1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [8]:
#power
z1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [9]:
# Modulo
z1 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

# Relational operators

The relational operators are also known as comparison operators, their main function is to return either a true or false based on the value of operands.

In [10]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
z2 > 2   #if 2 is greater than evrything gives true

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# Vector Operation

We can apply on both numpy array

In [14]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
z2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
# Arthemetic 
z1 + z2 #both numpy array shape is same, we can add item wise


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [17]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [18]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [19]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions

In [20]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[81., 14.,  7.],
       [36., 12., 95.],
       [73., 82., 31.]])

In [21]:
#max
np.max(k1)

95.0

In [22]:
#min
np.min(k1)

7.0

In [24]:
#sum
np.sum(k1)

431.0

In [25]:
#prod:Multiplication
np.prod(k1)

60452860144320.0

# In Numpy

0 = column, 1 = row

In [26]:
#if we want maximum of every row
np.max(k1, axis = 1)

array([81., 95., 82.])

In [27]:
#maximum of every column 
np.max(k1,axis=0)

array([81., 82., 95.])

In [28]:
# product of every column
np.prod(k1,axis=0)

array([212868.,  13776.,  20615.])

# Statistics related functions

In [29]:
#mean
k1

array([[81., 14.,  7.],
       [36., 12., 95.],
       [73., 82., 31.]])

In [30]:
np.mean(k1)

47.888888888888886

In [32]:
# mean of every column
k1.mean(axis=0)

array([63.33333333, 36.        , 44.33333333])

In [33]:
# median
np.median(k1)

36.0

In [34]:
np.median(k1, axis = 1)

array([14., 36., 73.])

In [35]:
# Standard deviation
np.std(k1)

32.73613173525018

In [36]:
np.std(k1,axis=0)

array([19.60158724, 32.53715825, 37.14236874])

In [37]:
# variance
np.var(k1)

1071.6543209876543